#!/usr/bin/env sh

alias reload='source ~/.bashrc'
alias reset='source ~/.bashrc; clear; cd;'
alias up='cd ..;'
alias up1='cd ..;'
alias up2='cd ../../;'
alias up3='cd ../../../;'
alias up4='cd ../../../;'
alias wget="curl -O"
alias d='pwd'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

IS_LS_BSD=`ls --color 2>&1 >/dev/null`
LS_COLOR="--color=auto"
[ "$IS_LS_BSD" ] && LS_COLOR="-G"

alias ls="ls -lhA $LS_COLOR"
alias l="ls $LS_COLOR"

[ "$IS_LS_BSD" ] && alias la='ls -leO@'
