#!/usr/bin/env sh

alias reload='source ~/.bashrc'
alias reset='source ~/.bashrc; clear; cd;'
alias up='cd ..;'
alias up1='cd ..;'
alias up2='cd ../../;'
alias up3='cd ../../../;'
alias up4='cd ../../../;'

if [ $COLORS ]; then
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias ls='ls -lhAG'
    alias l='ls -G'
else
    alias ls='ls -lhA'
    alias l='ls -A'
fi
alias la='ls -leO@'

alias wget="curl -O"

alias d='pwd'
