#!/usr/bin/env sh

function ps1_main {
    prompt="$CLR_WHITE\h $CLR_YELLOW@$CLR_WHITE\T$CLR_END $CLR_BLUE\W$CLR_END $CLR_GRAY ℋ  $CLR_END"
    repo=`git_repo`
    if [ "$repo" ]; then
        ref=`git_ref`
        repo=`git_repo`
        if [ "$ref" ]; then
            prompt="$CLR_GRAY<$CLR_LTGRAY$repo$CLR_GRAY|$CLR_LTGRAY$ref$CLR_END$CLR_GRAY>$CLR_END $prompt"
        fi
    fi
    if [ "$VIRTUAL_ENV" ]; then
        prompt="$CLR_GRAY[`basename $VIRTUAL_ENV`]$CLR_END $prompt"
    fi
    PS1="$prompt"
}

export PROMPT_COMMAND=ps1_main
