#!/usr/bin/env sh

alias dotupdate='dotup'
alias updatedots='dotup'
alias updots='dotup'
alias dotuninstall='dotdown'
alias rmdots='dotdown'
alias dot='cd $DOTFILES; ls;'
alias dots='cd $DOTFILES_SRC; ls;'
alias dotl='cd $DOTFILES_LOCAL; ls;'
