#!/usr/bin/env sh

# Virtual Environment activation
function activate_virtualenv {
    if [[ -z $WORKON_HOME ]]
    then
        return
    fi
    local venv=`find $WORKON_HOME -maxdepth 1 -type d -name $1`
    if [[ ! -z $venv ]]
    then
        workon $1
    fi
}

# Navigation
alias work='cd $HOME/Work'

# Work

# Socrata
alias wal-e="cd /Users/brianoldfield/Work/third-party/wal-e;activate_virtualenv wal-e"
alias post-review="rbt post -g --target-groups=sysadmin -p"
alias chef-repo="cd /Users/brianoldfield/Work/Socrata/chef-repo"
alias azure-chef-repo="cd /Users/brianoldfield/Work/Socrata/azure-chef-repo"

# Personal
alias decanter='cd $HOME/Work/decanter;activate_virtualenv decanter'
alias bottler='cd $HOME/Work/oldfield.io/bottler/bottler;activate_virtualenv bottler'
alias oldfieldwww='cd $HOME/Work/oldfield.io/oldfieldwww;activate_virtualenv oldfieldwww'
alias oldfield.io='cd $HOME/Work/oldfield.io/oldfield.io;activate_virtualenv oldfieldio'
alias merrychristmaswww='cd $HOME/Work/merrychristm.as/merrychristmaswww;activate_virtualenv christmaswww'
alias merrychristm.as='cd $HOME/Work/merrychristm.as/merrychristm.as;activate_virtualenv christm.as'
alias resume='cd $HOME/Documents/Resume'
alias books='cd $HOME/Work/Books/'

## TopCoder
alias tc='cd $HOME/Work/TopCoder/'
alias ilc='cd $HOME/Work/TopCoder/ILC'

## Class
alias class='cd $HOME/Work/Class'
alias compilers='cd $HOME/Work/Class/Coursera/Compilers.003'

# Altefeld
alias om='cd $HOME/Work/OptionMinder;activate_virtualenv om'
alias btcm='cd $HOME/Work/Altefeld/BitMarket;activate_virtualenv btcm'
alias de='cd $HOME/Work/Altefeld/DeepEnd'

# oDesk
alias solar-api='cd $HOME/Work/odesk/NealEdgeworth/SolarAPI;activate_virtualenv solar-api'

# App shortcuts
alias iphone="open $DOTFILES/src/bin/iPhone\ Simulator.app"
